name: hallo_doctor_doctor_app
version: 1.0.0
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  google_sign_in: ^7.0.0
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.3
  fluttertoast: ^8.0.8
  google_fonts: ^5.1.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.7
  flutter_svg: ^1.0.1
  get_storage: ^2.0.3
  table_calendar: ^3.0.3
  flutter_form_builder: ^9.1.0
  form_builder_validators: ^9.0.0
  cached_network_image: ^3.3.0
  string_validator: ^0.3.0
  lottie: ^3.1.2
  date_count_down:
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^4.1.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  cloud_functions: ^5.0.4
  firebase_storage: ^12.1.3
  firebase_database: ^11.3.7
  firebase_messaging: ^15.0.4
  flutter_dotenv: ^5.0.2
  flutter_chat_ui:
    git:
      url: https://github.com/amsyary/flutter_chat_ui.git
  # flutter_chat_ui:
  #   path: ../../DancingWhale/Migrasi Error Package Change Name/flutter_chat_ui
  #   # path: ../flutter_chat_ui
  uuid: ^3.0.6
  file_picker: ^10.2.0
  mime: ^1.0.1
  jiffy: ^5.0.0
  flutter_local_notifications: ^17.2.2
  dropdown_search: ^5.0.6
  json_serializable: ^6.1.5
  json_annotation: ^4.4.0
  agora_rtc_engine: ^5.3.0
  permission_handler: ^9.2.0
  image_cropper: ^5.0.0
  currency_text_input_formatter: ^2.1.8
  open_file_plus: ^3.4.0
  freezed_annotation: ^2.4.1
  external_app_launcher: ^3.1.0
  change_app_package_name: ^1.5.0
  rename_app: ^1.6.2
  flutter_native_splash: ^2.2.16
  url_launcher_ios: ^6.3.3

dependency_overrides:
  intl: 0.19.0
  win32: ^5.5.4
  archive: ^3.6.1

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.11
  freezed: ^2.4.3
  patrol: ^3.7.2

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"



  flutter_native_splash:
    color: "#ffffff"
    image: assets/icons/ic_launcher.png
    android_gravity: fill
    android_12:
      image: assets/icons/ic_launcher.png
      icon_background_color: "#ffffff"
      android_gravity: fill
